apiVersion: v2
appVersion: 1.32.1
description: Scales Kubernetes worker nodes within autoscaling groups.
engine: gotpl
home: https://github.com/kubernetes/autoscaler
icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
name: cluster-autoscaler
type: application
version: 1.0.0
