apiVersion: v1
kind: Secret
metadata:
  name: actalis-eab-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # base64url-encoded, unpadded (no trailing '=')
  secret: {{ .Values.actalis.hmacKey | replace "=" "" | quote }}