{{- if .Values.actalis.issuers.enabled }}
{{- range .Values.actalis.issuers.list }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  acme:
    email: {{ $.Values.actalis.email | quote }}
    server: {{ $.Values.actalis.server | quote }}
    privateKeySecretRef:
      name: actalis-acme-account-key
    externalAccountBinding:
      keyID: {{ $.Values.actalis.kid | quote }}
      keySecretRef:
        name: actalis-eab-secret
        key: secret # contains Actalis hmacKey
    solvers:
      - http01:
          ingress:
            class: {{ $.Values.actalis.ingressClass | quote }}
{{- end }}
{{- end }}
