apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.metricsServiceName" . }}
  labels:
    control-plane: controller-manager
  {{- include "operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/name: aruba
    control-plane: controller-manager
    {{- include "operator.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.metricsService.ports | toYaml | nindent 2 }}
